### ISSUE TITLE
No response on "Go Back" Press 

### ISSUE THREAD

**Issue by jitenderbadoni** [cashfree/cashfree-pg-react#10]
When pressing Go Back on web view of Payment gateway no response received.

How do we track the Go back press if nothing received on response.?

![Screen Shot 2019-06-14 at 10 49 15 AM](https://user-images.githubusercontent.com/13301666/59485225-8177eb00-8e92-11e9-9857-93c3d100f3ae.jpg)

**Comment by jitenderbadoni** [comment]
@nafeydev Is this resolved.?

**Comment by nafeydev** [comment]
Please update to the latest version of our react library. It works there.

**Comment by jitenderbadoni** [comment]
Thanks!
