### ISSUE TITLE
Open Payment Page without Modal view

### ISSUE THREAD

**Issue by Louies89** [cashfree/cashfree-pg-react#12]
@nafeydev

Currently the cashfree implementation is opening the payment page in a modal container, where the app does not have enough control over it.

So instead of modal container, if payment page shall opens in  normal view component, the developer can add 
1. there own header and footer to the payment page
2. in case of error, developer can add there own error message component

I have modified the **index.js** file to implement the above points please check the below screen shots

![Screenshot_2020-02-03-19-33-27-670_com clenet](https://user-images.githubusercontent.com/30086899/73660110-90c7d500-46bd-11ea-8ba5-117a692c34db.png)

![Screenshot_2020-02-03-19-14-40-895_com clenet](https://user-images.githubusercontent.com/30086899/73660118-958c8900-46bd-11ea-92fe-31c30ea5569b.png)

And the code file is attached bellow :

[index.js.txt](https://github.com/cashfree/cashfree-pg-react/files/4148272/index.js.txt)

Also I have added the code :
            **onError={()=>{
              this.props.onError()
            }}**

**Comment by nafeydev** [comment]
Thanks for the suggestion. This has been forwarded to our Product team and will be considered for future realeses. Will be closing this issue as there is no immediate action that is pending.
