### ISSUE TITLE
Getting Error After Replace AppId in App.js

### ISSUE THREAD

**Issue by yadagiribalemula** [cashfree/cashfree-pg-react#5]
Please let me know how to integrate cashfree with react-native

![whatsapp image 2018-12-19 at 22 34 27](https://user-images.githubusercontent.com/26407387/50235642-59756680-03de-11e9-9ee9-23f674012287.jpeg)

**Comment by Madhuvanth** [comment]
Am getting something similar - "Failed to verify merchant credentials".

Did you manage to solve this? If yes, are you running it on a simulator or a physical device?

**Comment by nafeydev** [comment]
Please drop a mail to techsupport@cashfree.com for integration related issues.
