### ISSUE TITLE
onRequestClose prop required for modal warning

### ISSUE THREAD

**Issue by murtraja** [cashfree/cashfree-pg-react#7]
Hello, 
I am in the process of integrating cash free payment gateway in our react-native code base and I found this warning while trying to use it.

`Warning: Failed prop type: The prop onRequestClose is marked as required in Modal, but its value is undefined.`

I am using 
"react-native": "0.57.3",
"cashfreereactnativepg": "^1.2.4",

Please direct me to correct forum, if this is not the right place for my query.
Thanks,

**Comment by nafeydev** [comment]
This has been fixed in future releases. Feel free to reopen if you see this issue again.
